Fix invalid payload packet
Developer-Mike/Autototem-Fabric pull request #15
Opened 2024-10-25 14:00 UTC by jonesdevelopment

The server opt-out feature is currently sending a duplicate payload packet (non-vanilla behaviour) with the channel `minecraft:brand` which flags anti-cheat, anti-exploit, and anti-bot plugins.

As an anti-bot developer myself, I've received several reports of users who have this mod installed trying to join servers protected by my anti-bot plugin, [Sonar](<https://github.com/jonesdevelopment/sonar>).

This PR fixes this issue by using a custom payload channel instead of Minecraft's brand channel.

This way, servers are able to opt-out, and people no longer have problems logging in to some servers, especially the ones using my plugin.

2024-11-06 17:15 UTC, jonesdevelopment commented
@Developer-Mike bump

2024-11-07 16:19 UTC, Developer-Mike commented
I'll merge this if I have some spare time.

2024-11-23 10:52 UTC, jonesdevelopment commented
> I'll merge this if I have some spare time.

I've tested everything and it works perfectly fine. Please merge this and push an update to the mod so people don't use a broken version that sends invalid payload packets.

2024-12-03 16:57 UTC, jonesdevelopment commented
@Developer-Mike bump

2024-12-03 17:58 UTC, Developer-Mike requested changes
Please remove the comment and adjust the code style (two brackets on the next line).

2024-12-03 19:11 UTC, Developer-Mike approved these changes

2024-12-03 19:11 UTC, merged